apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: deploy-cloudrun-dev
spec:
  template:
    spec:
      serviceAccountName: "{{.CLOUD_RUN_RUNNER_SA}}"
      containers:
        - image: "{{.GCR_REPOSITORY}}:latest"
          ports:
            - name: http1
              containerPort: 8080
          resources:
            limits:
              cpu: 1000m
              memory: 128Mi